modLoader="javafml"
loaderVersion="[34,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/BingoLobby/issues"

[[mods]]
modId="bingolobby"
version="${file.jarVersion}"
displayName="BingoLobby"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bingolobby"
authors="noeppi_noeppi"
description='''
A lobby for the Bongo mod.
'''

[[dependencies.bingolobby]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingolobby]]
    modId="bongo"
    mandatory=true
    versionRange="[1.0.23,)"
    ordering="NONE"
    side="BOTH"
